version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test-python3:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            pip install mock
            pip install requests
      - run:
          name: Run tests
          command: python -m unittest discover

  build-and-test-python2:
    docker:
      - image: cimg/python:2.7.18
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            pip install mock
            pip install requests
      - run:
          name: Run tests
          command: python -m unittest discover

workflows:
  build-and-test-wf:
    jobs:
      - build-and-test-python3
      - build-and-test-python2
