version: 2.1

orbs:
  python: circleci/python@2.1.1

commands:
  install-dependencies-run-tests:
    parameters:
      mock-version:
        type: string
      requests-version:
        type: string
    steps:
      - run:
          name: Install test dependencies
          command: |
            pip install mock==<<parameters.mock-version>>
            pip install requests==<<parameters.requests-version>>
      - run:
          name: Run tests
          command: python -m unittest discover

jobs:
  build-and-test-python3:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - install-dependencies-run-tests:
          mock-version: 5.0.1
          requests-version: 2.28.2

  build-and-test-python2:
    docker:
      - image: cimg/python:2.7.18
    steps:
      - checkout
      - install-dependencies-run-tests:
          mock-version: 3.0.5
          requests-version: 2.27.1

  run-integration-tests-python3:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: | 
            cd sift-python
            pip3 install ../sift-python
            python3 test_integration_app/main.py

workflows:
  build-and-test-wf:
    jobs:
#      - build-and-test-python3
#      - build-and-test-python2
      - run-integration-tests-python3:
          filters:
            branches:
              only: API-7364-testing-app-in-ci
