name: CI-WORKFLOW

on:
  push:
    branches: [ "CI-16181" ]
  pull_request:
    branches: [ "CI-16181" ]

permissions:
  contents: read

env:
  mock_version_python3: "5.0.1"
  requests_version_python3: "2.28.2"
  mock_version_python2: "3.0.5"
  requests_version_python2: "2.27.1"
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-and-test-python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"
      - name: Install test dependencies
        run: |
          pip install mock==5.0.1
          pip install requests==2.28.2
      - name: Run tests
        run: |
          python -m unittest discover

  run-integration-tests-python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"
      - name: Install test dependencies
        run: |
          pip3 install .
          python3 test_integration_app/main.py
