name: CI-WORKFLOW

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

env:
  mock_version_python2: "3.0.5"
  requests_version_python2: "2.27.1"
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

inputs:
  version:
    mock_version_python3: "5.0.1"
    requests_version_python3: "2.28.2"

jobs:
  build-and-test-python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"
      - name: Install test dependencies
        run: |
          pip install mock==${{ inputs.version.mock_version_python3 }}
          pip install requests==${{ inputs.version.requests_version_python3 }}
      - name: Run tests
        run: |
          python -m unittest discover

  run-integration-tests-python3:
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"
      - name: run-integration-tests-python3
        if: ${{ env.PUSH_PACKAGES }}
        run: |
          pip3 install .
          python3 test_integration_app/main.py
