name: CI-WORKFLOW

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-and-test-python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"
      - name: Install test dependencies
        run: |
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Run linters
        run: |
          pip install -U pre-commit
          pre-commit run -v --all-files
      - name: Run tests
        run: |
          python -m unittest discover

  run-integration-tests-python3:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"
      - name: Run integration tests
        run: |
          pip install .
          python test_integration_app/main.py
